language: node_js
addons:
  ssh_known_hosts: 167.99.6.108
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d

- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

- env
- ls ~/.ssh -la
- cat ~/.ssh/authorized_keys
- cat ~/.ssh/known_hosts

- ssh -t root@167.99.6.108 touch /root/projects/foo
script:
- echo "Scripting"
deploy:
- echo "Ola travis"
