version: '2'
services:
  jenkins:
    restart: always
    image: jenkins/jenkins:lts
    volumes:
      - ~/projects/victor/yousages/data/jenkins:/var/jenkins_home
    ports:
      - 8080:8080
      - 5000:5000